using System;
using System.Collections.Generic;

namespace CitiDownloader.models.entities
{
    public partial class Courses
    {
        public string CourseId { get; set; }
        public int InternalId { get; set; }
        public bool? SystemUseOnly { get; set; }
        public string ParentCourseId { get; set; }
        public string CourseTypeId { get; set; }
        public string Title { get; set; }
        public string Delivery { get; set; }
        public string Category { get; set; }
        public string Subcategory { get; set; }
        public int? DisplaySequence { get; set; }
        public string InternalVersion { get; set; }
        public string Description { get; set; }
        public bool? MultiSessionCourse { get; set; }
        public bool? MultiTopicCourse { get; set; }
        public int? ExpireDays { get; set; }
        public DateTime? DateAdded { get; set; }
        public double? Duration { get; set; }
        public string DurationUm { get; set; }
        public double? Cost { get; set; }
        public string CostUm { get; set; }
        public string Status { get; set; }
        public string PreReqs { get; set; }
        public string CbtlaunchPath { get; set; }
        public string CbtlaunchParameters { get; set; }
        public int? CbtwinWidth { get; set; }
        public int? CbtwinHeight { get; set; }
        public string CbtwinOptions { get; set; }
        public int? MaximumSize { get; set; }
        public int? WaitlistSize { get; set; }
        public int? RegOpenDays { get; set; }
        public int? RegCloseDays { get; set; }
        public string OtherInformation { get; set; }
        public double? Ceu { get; set; }
        public int? DebugLevel { get; set; }
        public int? MinimumSize { get; set; }
        public bool? UserCanCancel { get; set; }
        public string VendorId { get; set; }
        public string VendorContact { get; set; }
        public int? Quantity { get; set; }
        public bool? AssessmentPrintFlag { get; set; }
        public bool? CertificatePrintFlag { get; set; }
        public bool? UserFlag1 { get; set; }
        public bool? UserFlag2 { get; set; }
        public bool? UserFlag3 { get; set; }
        public bool? UserFlag4 { get; set; }
        public bool? UserFlag5 { get; set; }
        public bool? UserFlag6 { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public DateTime? UserDate4 { get; set; }
        public DateTime? UserDate5 { get; set; }
        public DateTime? UserDate6 { get; set; }
        public int? SignatureRequired { get; set; }
        public string ShortDescription { get; set; }
        public string AlternateCourseId { get; set; }
        public string CertificateLogo { get; set; }
        public bool? LaunchInPopUp { get; set; }
        public string EnrollmentRuleId { get; set; }
        public int? TrainingAreaKey { get; set; }
        public bool? ShowInStorefront { get; set; }
        public bool? CountFailedAsComplete { get; set; }
        public string ECommerceCategoryId { get; set; }
        public string ECommerceSubcategoryId { get; set; }
        public string TrainingAreaName { get; set; }
        public string CourseTypeName { get; set; }
        public string CourseLaunchTypeId { get; set; }
        public string CourseUnitTypeName { get; set; }
        public string CategoryName { get; set; }
        public string SubcategoryName { get; set; }
        public string User1Name { get; set; }
        public string User2Name { get; set; }
        public string User3Name { get; set; }
        public string User4Name { get; set; }
        public string User5Name { get; set; }
        public string User6Name { get; set; }
        public DateTime? DateEffectiveFrom { get; set; }
        public DateTime? DateEffectiveTo { get; set; }
        public string PlainTextDescription { get; set; }
        public int? ExpiryBasisId { get; set; }
        public int? ExpiryWarningDays { get; set; }
        public int? ExpiryGraceDays { get; set; }
        public string ArchiveMethod { get; set; }
        public int? DomainKey { get; set; }
        public bool? UserCanReview { get; set; }
        public bool? SuppressWorkflow { get; set; }
        public int? ArchiveDays { get; set; }
        public string DomainName { get; set; }
        public int? DiscussionAudience { get; set; }
        public string CertificateBackground { get; set; }
        public string CertificateSignature { get; set; }
        public int? LocationKey { get; set; }
        public string LocationName { get; set; }
        public string Manager1Id { get; set; }
        public string Manager2Id { get; set; }
        public string Manager3Id { get; set; }
    }
}
