using System;
using System.Collections.Generic;

namespace TrainingDownloader.models.entities
{
    public partial class Learners
    {
        public string LearnerId { get; set; }
        public bool? SystemUseOnly { get; set; }
        public int InternalId { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public string FirstName { get; set; }
        public string SalutationId { get; set; }
        public string TitleId { get; set; }
        public string DepartmentId { get; set; }
        public int? LocationKey { get; set; }
        public int? CompanyKey { get; set; }
        public int? DivisionKey { get; set; }
        public int? RegionKey { get; set; }
        public string RecordStatusId { get; set; }
        public string LearnerTypeId { get; set; }
        public string LearnerUnionId { get; set; }
        public string LearnerStatusId { get; set; }
        public string LanguageId { get; set; }
        public string GenderId { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Notes { get; set; }
        public DateTime? HireDate { get; set; }
        public DateTime? TerminateDate { get; set; }
        public string InsertTypeId { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UserId { get; set; }
        public string Pin { get; set; }
        public bool? PasswordChange { get; set; }
        public DateTime? PasswordExpiryDate { get; set; }
        public DateTime? AccountExpiryDate { get; set; }
        public string AuthorizationCode { get; set; }
        public string ManagerId { get; set; }
        public string Signature { get; set; }
        public string SecurityProfileId { get; set; }
        public string TrainerTypeId { get; set; }
        public bool? LearnerMustLogin { get; set; }
        public bool? LearnerMustLogout { get; set; }
        public bool? UserFlag1 { get; set; }
        public bool? UserFlag2 { get; set; }
        public bool? UserFlag3 { get; set; }
        public bool? UserFlag4 { get; set; }
        public bool? UserFlag5 { get; set; }
        public bool? UserFlag6 { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public DateTime? UserDate4 { get; set; }
        public DateTime? UserDate5 { get; set; }
        public DateTime? UserDate6 { get; set; }
        public double? UserFloat1 { get; set; }
        public double? UserFloat2 { get; set; }
        public double? UserFloat3 { get; set; }
        public double? UserFloat4 { get; set; }
        public double? UserFloat5 { get; set; }
        public double? UserFloat6 { get; set; }
        public string TimeZone { get; set; }
        public string EmploymentBasisId { get; set; }
        public string Manager2Id { get; set; }
        public string Manager3Id { get; set; }
        public string NickName { get; set; }
        public string ProfilePicture { get; set; }
        public DateTime? LastActionDate { get; set; }
        public string LastActionType { get; set; }
        public string TitleName { get; set; }
        public string DepartmentName { get; set; }
        public string CompanyName { get; set; }
        public string RegionName { get; set; }
        public string DivisionName { get; set; }
        public string LocationName { get; set; }
        public string User1Name { get; set; }
        public string User2Name { get; set; }
        public string User3Name { get; set; }
        public string User4Name { get; set; }
        public string User5Name { get; set; }
        public string User6Name { get; set; }
        public string NameFull { get; set; }
        public string NameReverse { get; set; }
        public DateTime? LaunchDate { get; set; }
        public int? DomainKey { get; set; }
        public string DomainName { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public string ForgotPasswordUid { get; set; }
        public string ForgotPasswordDateTimeStamp { get; set; }
    }
}
